#!/usr/bin/env sh
# Generated by the `record` module; edits will be replaced.
# Usage: smia-record [toggle|start|stop|status] [screen|region]
set -eu
set -f
umask 077

DIR={{directory:shell-word}}
FPS="{{fps}}"
AUDIO_SOURCE={{audio-source:shell-word}}
SCREEN_TARGET={{screen-target:shell-word}}
STATE_VERSION="smia-record-v2"
START_GRACE="0.20"
STOP_GRACE="5.0"
RUNTIME_DIR=""
STATEFILE=""
LOCKFILE=""
LOGFILE=""
STATE_TMP=""
REQUEST_DIR=""
USER_ID=""

STATE_SESSION=""
STATE_TOKEN=""
STATE_OUTPUT=""
SESSION_DIR=""
CONTROL_FIFO=""
LEASE_FILE=""
OUTPUT_FILE=""
STATE_CHANNEL_OK=false

usage() {
    echo "Usage: smia-record [toggle|start|stop|status [--waybar]] [screen|region]" >&2
    exit 2
}

die() {
    printf 'smia-record: %s\n' "$*" >&2
    exit 1
}

notify() {
    command -v notify-send >/dev/null 2>&1 && notify-send "$@" || printf '%s\n' "$*" >&2
}

signal_waybar() {
    pkill -RTMIN+8 waybar >/dev/null 2>&1 || true
}

cleanup_temp() {
    [ -z "$STATE_TMP" ] || rm -f "$STATE_TMP"
    [ -z "$REQUEST_DIR" ] || rm -rf "$REQUEST_DIR"
}

trap cleanup_temp 0

resolve_output_directory() {
    case "$DIR" in
        "~")
            [ -n "${HOME:-}" ] || die "HOME is not set"
            case "$HOME" in /*) ;; *) die "HOME must be absolute" ;; esac
            DIR="$HOME"
            ;;
        "~/"*)
            [ -n "${HOME:-}" ] || die "HOME is not set"
            case "$HOME" in /*) ;; *) die "HOME must be absolute" ;; esac
            DIR="$HOME/${DIR#\~/}"
            ;;
        /*) ;;
        *) die "output directory must be absolute or start with ~/" ;;
    esac
}

directory_metadata() {
    stat -c '%u %A' "$1" 2>/dev/null
}

safe_owned_directory() {
    [ -d "$1" ] && [ ! -L "$1" ] || return 1
    metadata="$(directory_metadata "$1")" || return 1
    set -- $metadata
    [ "$#" -eq 2 ] && [ "$1" = "$USER_ID" ] || return 1
    case "$2" in
        d????w????|d???????w?) return 1 ;;
        d?????????) return 0 ;;
        *) return 1 ;;
    esac
}

private_owned_directory() {
    [ -d "$1" ] && [ ! -L "$1" ] || return 1
    metadata="$(stat -c '%u %a' "$1" 2>/dev/null)" || return 1
    set -- $metadata
    [ "$#" -eq 2 ] && [ "$1" = "$USER_ID" ] && [ "$2" = "700" ]
}

private_owned_file() {
    [ -f "$1" ] && [ ! -L "$1" ] || return 1
    metadata="$(stat -c '%u %a' "$1" 2>/dev/null)" || return 1
    set -- $metadata
    [ "$#" -eq 2 ] && [ "$1" = "$USER_ID" ] && [ "$2" = "600" ]
}

private_owned_file_descriptor() {
    [ -f "$1" ] || return 1
    metadata="$(stat -Lc '%u %a' "$1" 2>/dev/null)" || return 1
    set -- $metadata
    [ "$#" -eq 2 ] && [ "$1" = "$USER_ID" ] && [ "$2" = "600" ]
}

private_owned_fifo() {
    [ -p "$1" ] && [ ! -L "$1" ] || return 1
    metadata="$(stat -c '%u %a' "$1" 2>/dev/null)" || return 1
    set -- $metadata
    [ "$#" -eq 2 ] && [ "$1" = "$USER_ID" ] && [ "$2" = "600" ]
}

ensure_owned_directory() {
    directory="$1"
    if [ ! -e "$directory" ] && [ ! -L "$directory" ]; then
        mkdir "$directory" 2>/dev/null || true
    fi
    safe_owned_directory "$directory" || die "unsafe runtime parent: $directory"
}

ensure_private_directory() {
    directory="$1"
    if [ ! -e "$directory" ] && [ ! -L "$directory" ]; then
        mkdir "$directory" 2>/dev/null || true
    fi
    private_owned_directory "$directory" \
        || die "runtime directory must be owned by the current user with mode 0700: $directory"
}

init_runtime() {
    USER_ID="$(id -u)" || die "cannot determine the current user"
    case "$USER_ID" in ''|*[!0-9]*) die "invalid current user id" ;; esac

    if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
        case "$XDG_RUNTIME_DIR" in /*) ;; *) die "XDG_RUNTIME_DIR must be absolute" ;; esac
        private_owned_directory "$XDG_RUNTIME_DIR" \
            || die "XDG_RUNTIME_DIR must be owned by the current user with mode 0700"
        RUNTIME_DIR="$XDG_RUNTIME_DIR/smia-record"
        ensure_private_directory "$RUNTIME_DIR"
    else
        case "${HOME:-}" in /*) ;; *) die "HOME must be set to an absolute path when XDG_RUNTIME_DIR is unset" ;; esac
        safe_owned_directory "$HOME" || die "HOME is not a safely owned directory"
        ensure_owned_directory "$HOME/.local"
        ensure_owned_directory "$HOME/.local/state"
        ensure_owned_directory "$HOME/.local/state/smia"
        RUNTIME_DIR="$HOME/.local/state/smia/record"
        ensure_private_directory "$RUNTIME_DIR"
    fi

    STATEFILE="$RUNTIME_DIR/active"
    LOCKFILE="$RUNTIME_DIR/lock"
    LOGFILE="$RUNTIME_DIR/recorder.log"
}

lock_state() {
    if [ -e "$LOCKFILE" ] || [ -L "$LOCKFILE" ]; then
        private_owned_file "$LOCKFILE" || die "unsafe recorder lock file"
    fi
    exec 9>>"$LOCKFILE" || die "cannot open recorder lock"
    private_owned_file_descriptor "/proc/$$/fd/9" || die "unsafe recorder lock descriptor"
    path_identity="$(stat -Lc '%d:%i' "$LOCKFILE" 2>/dev/null)" || die "cannot inspect recorder lock"
    fd_identity="$(stat -Lc '%d:%i' "/proc/$$/fd/9" 2>/dev/null)" || die "cannot inspect recorder lock"
    [ "$path_identity" = "$fd_identity" ] || die "recorder lock changed while opening"
    flock -w 15 -x 9 || die "cannot lock recorder state"
}

valid_session_name() {
    case "$1" in
        session.*)
            suffix=${1#session.}
            case "$suffix" in ''|*[!A-Za-z0-9]*) return 1 ;; esac
            ;;
        *) return 1 ;;
    esac
}

valid_token() {
    [ "${#1}" -eq 64 ] || return 1
    case "$1" in *[!0-9a-f]*) return 1 ;; esac
}

set_session_paths() {
    SESSION_DIR="$RUNTIME_DIR/$STATE_SESSION"
    CONTROL_FIFO="$SESSION_DIR/control"
    LEASE_FILE="$SESSION_DIR/lease"
    OUTPUT_FILE="$SESSION_DIR/output"
}

lease_is_held() {
    private_owned_file "$LEASE_FILE" || return 1
    exec 8<"$LEASE_FILE" || return 1
    path_identity="$(stat -Lc '%d:%i' "$LEASE_FILE" 2>/dev/null)" || {
        exec 8>&-
        return 1
    }
    fd_identity="$(stat -Lc '%d:%i' "/proc/$$/fd/8" 2>/dev/null)" || {
        exec 8>&-
        return 1
    }
    if [ "$path_identity" != "$fd_identity" ]; then
        exec 8>&-
        return 1
    fi
    if flock -n -x 8 2>/dev/null; then
        flock -u 8 2>/dev/null || true
        exec 8>&-
        return 1
    fi
    exec 8>&-
    return 0
}

cleanup_known_session() {
    [ -n "$SESSION_DIR" ] || return 0
    private_owned_directory "$SESSION_DIR" || return 0
    lease_is_held && return 0
    rm -rf "$SESSION_DIR"
}

discard_state() {
    rm -f "$STATEFILE" 2>/dev/null || true
    cleanup_known_session
    signal_waybar
}

load_state() {
    STATE_SESSION=""
    STATE_TOKEN=""
    STATE_OUTPUT=""
    SESSION_DIR=""
    CONTROL_FIFO=""
    LEASE_FILE=""
    OUTPUT_FILE=""
    STATE_CHANNEL_OK=false

    [ -e "$STATEFILE" ] || [ -L "$STATEFILE" ] || return 1
    if ! private_owned_file "$STATEFILE"; then
        discard_state
        return 1
    fi
    if ! {
        IFS= read -r state_version &&
        IFS= read -r STATE_SESSION &&
        IFS= read -r STATE_TOKEN &&
        ! IFS= read -r state_extra
    } <"$STATEFILE"; then
        discard_state
        return 1
    fi
    if [ "$state_version" != "$STATE_VERSION" ] \
        || ! valid_session_name "$STATE_SESSION" \
        || ! valid_token "$STATE_TOKEN"; then
        discard_state
        return 1
    fi

    set_session_paths
    if ! private_owned_directory "$SESSION_DIR" || ! private_owned_file "$LEASE_FILE"; then
        discard_state
        return 1
    fi
    if ! private_owned_fifo "$CONTROL_FIFO" || ! private_owned_file "$OUTPUT_FILE" \
        || ! {
            IFS= read -r STATE_OUTPUT &&
            ! IFS= read -r output_extra
        } <"$OUTPUT_FILE" \
        || [ -z "$STATE_OUTPUT" ]; then
        if lease_is_held; then
            return 0
        fi
        discard_state
        return 1
    fi
    case "$STATE_OUTPUT" in /*) ;; *) discard_state; return 1 ;; esac
    return 0
}

control_request() {
    request_command="$1"
    request_timeout="$2"
    REQUEST_DIR="$(mktemp -d "$SESSION_DIR/request.XXXXXXXXXXXX")" || return 1
    request_name=${REQUEST_DIR##*/}
    reply_fifo="$REQUEST_DIR/reply"
    if ! mkfifo -m 600 "$reply_fifo"; then
        rm -rf "$REQUEST_DIR"
        REQUEST_DIR=""
        return 1
    fi

    request_rc=0
    python3 - "$CONTROL_FIFO" "$reply_fifo" "$STATE_TOKEN" \
        "$request_command" "$request_timeout" "$request_name" <<'PY' || request_rc=$?
import errno
import os
import select
import stat
import sys
import time

control_path, reply_path, token, command, timeout_text, request = sys.argv[1:]
timeout = float(timeout_text)
uid = os.getuid()
nofollow = getattr(os, "O_NOFOLLOW", 0)
cloexec = getattr(os, "O_CLOEXEC", 0)


def open_fifo(path, flags):
    before = os.lstat(path)
    if (not stat.S_ISFIFO(before.st_mode) or before.st_uid != uid
            or stat.S_IMODE(before.st_mode) != 0o600):
        raise OSError(errno.EINVAL, "unsafe fifo")
    fd = os.open(path, flags | os.O_NONBLOCK | nofollow | cloexec)
    after = os.fstat(fd)
    if (after.st_dev != before.st_dev or after.st_ino != before.st_ino
            or not stat.S_ISFIFO(after.st_mode) or after.st_uid != uid
            or stat.S_IMODE(after.st_mode) != 0o600):
        os.close(fd)
        raise OSError(errno.EINVAL, "fifo changed while opening")
    return fd


reply_fd = control_fd = None
try:
    reply_fd = open_fifo(reply_path, os.O_RDWR)
    control_fd = open_fifo(control_path, os.O_WRONLY)
    payload = (token + " " + command + " " + request + "\n").encode("ascii")
    if len(payload) > 512 or os.write(control_fd, payload) != len(payload):
        raise OSError(errno.EAGAIN, "short fifo write")

    deadline = time.monotonic() + timeout
    response = bytearray()
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError
        readable, _, _ = select.select([reply_fd], [], [], remaining)
        if not readable:
            raise TimeoutError
        chunk = os.read(reply_fd, 1024)
        if not chunk:
            continue
        response.extend(chunk)
        if len(response) > 1024:
            raise OSError(errno.EOVERFLOW, "oversized response")
        if b"\n" in response:
            line, extra = bytes(response).split(b"\n", 1)
            if extra:
                raise OSError(errno.EPROTO, "invalid response")
            print(line.decode("ascii"))
            break
except (OSError, TimeoutError, UnicodeError, ValueError):
    sys.exit(3)
finally:
    if control_fd is not None:
        os.close(control_fd)
    if reply_fd is not None:
        os.close(reply_fd)
PY
    rm -rf "$REQUEST_DIR"
    REQUEST_DIR=""
    return "$request_rc"
}

finish_inactive() {
    rm -f "$STATEFILE" 2>/dev/null || true
    control_request ACK 0.5 >/dev/null 2>&1 || true
    cleanup_known_session
    signal_waybar
}

recording_state() {
    load_state || return 1

    if ! private_owned_fifo "$CONTROL_FIFO" || ! private_owned_file "$OUTPUT_FILE"; then
        if lease_is_held; then
            return 0
        fi
        discard_state
        return 1
    fi

    response=""
    if response="$(control_request STATUS 1.0 2>/dev/null)"; then
        case "$response" in
            RECORDING|STARTING)
                STATE_CHANNEL_OK=true
                return 0
                ;;
            IDLE)
                finish_inactive
                return 1
                ;;
        esac
    fi

    if lease_is_held; then
        return 0
    fi
    discard_state
    return 1
}

write_state() {
    STATE_TMP="$(mktemp "$RUNTIME_DIR/.active.XXXXXXXXXXXX")" || return 1
    if ! printf '%s\n%s\n%s\n' "$STATE_VERSION" "$STATE_SESSION" "$STATE_TOKEN" >"$STATE_TMP" \
        || ! mv -f "$STATE_TMP" "$STATEFILE"; then
        cleanup_temp
        STATE_TMP=""
        return 1
    fi
    STATE_TMP=""
}

prepare_log() {
    STATE_TMP="$(mktemp "$RUNTIME_DIR/.recorder.log.XXXXXXXXXXXX")" || return 1
    if ! mv -f "$STATE_TMP" "$LOGFILE"; then
        cleanup_temp
        STATE_TMP=""
        return 1
    fi
    STATE_TMP=""
}

prepare_session() {
    SESSION_DIR="$(mktemp -d "$RUNTIME_DIR/session.XXXXXXXXXXXX")" || return 1
    STATE_SESSION=${SESSION_DIR##*/}
    STATE_TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(32))')" || return 1
    set_session_paths
    mkfifo -m 600 "$CONTROL_FIFO" || return 1
    : >"$LEASE_FILE" || return 1
    exec 8<"$LEASE_FILE" || return 1
    flock -n -x 8 || return 1
    printf '%s\n' "$STATE_OUTPUT" >"$OUTPUT_FILE" || return 1
    prepare_log || return 1
    write_state
}

report_recorder_failure() {
    if grep -q sys_admin "$LOGFILE" 2>/dev/null; then
        notify "Screen Recording" "KMS capture needs a one-time setup:
sudo setcap cap_sys_admin+ep /usr/bin/gsr-kms-server"
    else
        notify "Screen Recording" "Recorder failed; see $LOGFILE"
    fi
}

launch_supervisor() {
    (
        exec 9>&-
        python3 - "$SESSION_DIR" "$STATEFILE" "$LOCKFILE" "$LOGFILE" \
            "$STATE_VERSION" "$STATE_SESSION" "$STATE_TOKEN" "$STATE_OUTPUT" \
            "$START_GRACE" "$STOP_GRACE" "$@" <<'PY'
import ctypes
import errno
import fcntl
import hmac
import os
import re
import select
import shutil
import signal
import stat
import subprocess
import sys
import time

(session_dir, state_file, lock_file, log_file, state_version,
 session_name, token, output, start_grace_text, stop_grace_text) = sys.argv[1:11]
recorder_argv = sys.argv[11:]
start_grace = float(start_grace_text)
stop_grace = float(stop_grace_text)
uid = os.getuid()
nofollow = getattr(os, "O_NOFOLLOW", 0)
cloexec = getattr(os, "O_CLOEXEC", 0)
control_path = os.path.join(session_dir, "control")
lease_path = os.path.join(session_dir, "lease")
expected_state = (state_version + "\n" + session_name + "\n" + token + "\n").encode()
request_pattern = re.compile(r"request\.[A-Za-z0-9]+")


def checked_lstat(path, file_type, permissions):
    value = os.lstat(path)
    if (not file_type(value.st_mode) or value.st_uid != uid
            or stat.S_IMODE(value.st_mode) != permissions):
        raise OSError(errno.EINVAL, "unsafe runtime object: " + path)
    return value


def checked_open(path, flags, file_type, permissions):
    before = checked_lstat(path, file_type, permissions)
    fd = os.open(path, flags | nofollow | cloexec)
    after = os.fstat(fd)
    if (after.st_dev != before.st_dev or after.st_ino != before.st_ino
            or not file_type(after.st_mode) or after.st_uid != uid
            or stat.S_IMODE(after.st_mode) != permissions):
        os.close(fd)
        raise OSError(errno.EINVAL, "runtime object changed while opening")
    return fd


def read_private_file(path, maximum):
    fd = checked_open(path, os.O_RDONLY, stat.S_ISREG, 0o600)
    try:
        data = os.read(fd, maximum + 1)
    finally:
        os.close(fd)
    if len(data) > maximum:
        raise OSError(errno.EOVERFLOW, "oversized state")
    return data


def active_matches():
    try:
        return read_private_file(state_file, 1024) == expected_state
    except (FileNotFoundError, OSError):
        return False


def send_reply(request, response):
    if request_pattern.fullmatch(request) is None:
        return False
    request_dir = os.path.join(session_dir, request)
    reply_path = os.path.join(request_dir, "reply")
    fd = None
    try:
        checked_lstat(request_dir, stat.S_ISDIR, 0o700)
        fd = checked_open(
            reply_path,
            os.O_WRONLY | os.O_NONBLOCK,
            stat.S_ISFIFO,
            0o600,
        )
        payload = (response + "\n").encode("ascii")
        return os.write(fd, payload) == len(payload)
    except (FileNotFoundError, OSError, UnicodeError):
        return False
    finally:
        if fd is not None:
            os.close(fd)


def signal_waybar():
    try:
        subprocess.run(
            ["pkill", "-RTMIN+8", "waybar"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
    except OSError:
        pass


def notify_failure():
    try:
        with open(log_file, "rb") as stream:
            needs_capability = b"sys_admin" in stream.read(1024 * 1024)
        if needs_capability:
            message = ("KMS capture needs a one-time setup:\n"
                       "sudo setcap cap_sys_admin+ep /usr/bin/gsr-kms-server")
        else:
            message = "Recorder failed; see " + log_file
        subprocess.run(
            ["notify-send", "Screen Recording", message],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
    except OSError:
        pass


checked_lstat(session_dir, stat.S_ISDIR, 0o700)
if os.path.basename(session_dir) != session_name:
    raise SystemExit("session identity mismatch")
if read_private_file(state_file, 1024) != expected_state:
    raise SystemExit("active state mismatch")

state_lock_fd = checked_open(lock_file, os.O_RDWR, stat.S_ISREG, 0o600)
# Descriptor 8 carries the lease lock acquired before active state was
# published. Inheriting the same open file description leaves no startup gap.
lease_before = checked_lstat(lease_path, stat.S_ISREG, 0o600)
lease_fd = 8
lease_after = os.fstat(lease_fd)
if (lease_after.st_dev != lease_before.st_dev
        or lease_after.st_ino != lease_before.st_ino
        or not stat.S_ISREG(lease_after.st_mode)
        or lease_after.st_uid != uid
        or stat.S_IMODE(lease_after.st_mode) != 0o600):
    raise SystemExit("lease changed during supervisor handoff")
fcntl.flock(lease_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
control_fd = checked_open(
    control_path,
    os.O_RDONLY | os.O_NONBLOCK,
    stat.S_ISFIFO,
    0o600,
)
control_writer_fd = checked_open(
    control_path,
    os.O_WRONLY | os.O_NONBLOCK,
    stat.S_ISFIFO,
    0o600,
)

signal.signal(signal.SIGHUP, signal.SIG_IGN)
# Preserve exited children as zombies until the explicit WNOWAIT protocol has
# handled state; an inherited SIG_IGN/SA_NOCLDWAIT would permit PID recycling.
signal.signal(signal.SIGCHLD, signal.SIG_DFL)
try:
    os.setsid()
except OSError:
    pass

libc = ctypes.CDLL(None, use_errno=True)
parent_pid = os.getpid()


def arm_parent_death_signal():
    if libc.prctl(1, signal.SIGKILL, 0, 0, 0) != 0:
        os._exit(126)
    if os.getppid() != parent_pid:
        os._exit(126)


child = subprocess.Popen(
    recorder_argv,
    stdin=subprocess.DEVNULL,
    close_fds=True,
    preexec_fn=arm_parent_death_signal,
)
child_pid = child.pid
ready_at = time.monotonic() + start_grace
buffer = bytearray()
pending_stop = None
child_observation = None
announced = False
stop_requested = False
state_handled = False
state_removed = False


def observe_child():
    return os.waitid(
        os.P_PID,
        child_pid,
        os.WEXITED | os.WNOHANG | os.WNOWAIT,
    )


def try_handle_state():
    global state_removed
    try:
        fcntl.flock(state_lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        return False
    try:
        try:
            path_lock = os.lstat(lock_file)
            open_lock = os.fstat(state_lock_fd)
            if (path_lock.st_dev != open_lock.st_dev
                    or path_lock.st_ino != open_lock.st_ino):
                return True
        except OSError:
            return True
        if active_matches():
            try:
                os.unlink(state_file)
                state_removed = True
            except FileNotFoundError:
                pass
        return True
    finally:
        fcntl.flock(state_lock_fd, fcntl.LOCK_UN)


while not state_handled:
    now = time.monotonic()
    if child_observation is None:
        child_observation = observe_child()

    if child_observation is not None and pending_stop is not None:
        send_reply(pending_stop[0], "STOPPED")
        pending_stop = None
    elif (child_observation is None and pending_stop is not None
          and now >= pending_stop[1]):
        send_reply(pending_stop[0], "BUSY")
        pending_stop = None

    readable, _, _ = select.select([control_fd], [], [], 0.05)
    if readable:
        try:
            chunk = os.read(control_fd, 4096)
        except BlockingIOError:
            chunk = b""
        if chunk:
            buffer.extend(chunk)
            if len(buffer) > 8192:
                buffer.clear()
            while b"\n" in buffer:
                line, _, remainder = buffer.partition(b"\n")
                buffer = bytearray(remainder)
                try:
                    saved_token, command, request = line.decode("ascii").split(" ")
                except (UnicodeError, ValueError):
                    continue
                if request_pattern.fullmatch(request) is None:
                    continue
                if not hmac.compare_digest(saved_token, token):
                    send_reply(request, "DENIED")
                    continue

                if command == "STATUS":
                    if child_observation is not None:
                        send_reply(request, "IDLE")
                    elif time.monotonic() < ready_at:
                        send_reply(request, "STARTING")
                    elif send_reply(request, "RECORDING"):
                        announced = True
                elif command == "STOP":
                    if child_observation is not None:
                        send_reply(request, "STOPPED")
                    elif pending_stop is not None:
                        send_reply(request, "BUSY")
                    else:
                        stop_requested = True
                        try:
                            # The child is deliberately unreaped, so this PID
                            # cannot be recycled between observation and signal.
                            os.kill(child_pid, signal.SIGTERM)
                            pending_stop = (request, time.monotonic() + stop_grace)
                        except ProcessLookupError:
                            pending_stop = (request, time.monotonic() + stop_grace)
                        except OSError:
                            send_reply(request, "ERROR")
                elif command == "ACK":
                    if child_observation is not None and not active_matches():
                        send_reply(request, "ACKED")
                        state_handled = True
                    else:
                        send_reply(request, "DENIED")
                else:
                    send_reply(request, "DENIED")

    if child_observation is not None and not state_handled:
        state_handled = try_handle_state()

# State no longer names this session. Only now may the child be reaped.
_, wait_status = os.waitpid(child_pid, 0)
return_code = os.waitstatus_to_exitcode(wait_status)

os.close(control_writer_fd)
os.close(control_fd)
fcntl.flock(lease_fd, fcntl.LOCK_UN)
os.close(lease_fd)
os.close(state_lock_fd)
try:
    shutil.rmtree(session_dir)
except FileNotFoundError:
    pass

if state_removed:
    signal_waybar()
if announced and not stop_requested and return_code != 0:
    notify_failure()
PY
    ) >>"$LOGFILE" 2>&1 &
    # The background supervisor inherited descriptor 8 and its flock as the
    # same open file description, making state-to-supervisor handoff atomic.
    exec 8>&-
}

start() {
    target="${1:-screen}"
    if recording_state; then
        notify "Screen Recording" "Already recording"
        return 0
    fi

    mkdir -p "$DIR"
    STATE_OUTPUT="$DIR/Recording-$(date +%Y-%m-%d_%H%M%S).mp4"
    recorder="$(command -v gpu-screen-recorder)" || die "gpu-screen-recorder is not available"
    set -- "$recorder" -f "$FPS" -o "$STATE_OUTPUT"
    case "$target" in
        screen)
            set -- "$@" -w "$SCREEN_TARGET"
            [ "$SCREEN_TARGET" = portal ] && set -- "$@" -restore-portal-session yes
            ;;
        region)
            geom="$(slurp -f '%wx%h+%x+%y')" || return 0
            set -- "$@" -w region -region "$geom"
            ;;
        *) usage ;;
    esac
    [ -n "$AUDIO_SOURCE" ] && set -- "$@" -a "$AUDIO_SOURCE"

    if ! prepare_session; then
        cleanup_known_session
        die "recorder state could not be prepared"
    fi
    launch_supervisor "$@"

    attempt=0
    while [ "$attempt" -lt 40 ]; do
        response=""
        if response="$(control_request STATUS 0.25 2>/dev/null)"; then
            case "$response" in
                RECORDING)
                    signal_waybar
                    notify "Screen Recording" "Recording started"
                    return 0
                    ;;
                IDLE)
                    finish_inactive
                    report_recorder_failure
                    return 1
                    ;;
                STARTING) ;;
            esac
        fi
        if [ "$attempt" -ge 3 ] && ! lease_is_held; then
            break
        fi
        sleep 0.05
        attempt=$((attempt + 1))
    done

    if lease_is_held; then
        signal_waybar
        notify "Screen Recording" "Recorder supervisor did not become ready"
        return 1
    fi
    discard_state
    report_recorder_failure
    return 1
}

stop() {
    if ! recording_state; then
        notify "Screen Recording" "Not recording"
        return 0
    fi
    if [ "$STATE_CHANNEL_OK" != true ]; then
        notify "Screen Recording" "Recorder supervisor is not responding"
        return 1
    fi

    last="$STATE_OUTPUT"
    response=""
    if response="$(control_request STOP 6.0 2>/dev/null)"; then
        case "$response" in
            STOPPED)
                finish_inactive
                notify "Screen Recording" "Saved $last"
                return 0
                ;;
            BUSY)
                notify "Screen Recording" "Recorder is still finalizing; try again"
                return 1
                ;;
            IDLE)
                finish_inactive
                notify "Screen Recording" "Not recording"
                return 0
                ;;
        esac
    fi

    if lease_is_held; then
        notify "Screen Recording" "Recorder could not be stopped"
        return 1
    fi
    discard_state
    notify "Screen Recording" "Not recording"
}

status() {
    if recording_state; then
        echo recording
        return 0
    fi
    echo idle
    return 1
}

require_target() {
    case "$1" in screen|region) ;; *) usage ;; esac
}

MODE="${1:-toggle}"
WAYBAR=false
TARGET=""

case "$MODE" in
    status)
        if [ "${2:-}" = "--waybar" ]; then
            WAYBAR=true
        else
            [ "$#" -le 1 ] || usage
        fi
        ;;
    start|toggle)
        TARGET="${2:-screen}"
        require_target "$TARGET"
        ;;
    stop)
        [ "$#" -le 1 ] || usage
        ;;
    -h|--help)
        echo "Usage: smia-record [toggle|start|stop|status [--waybar]] [screen|region]"
        exit 0
        ;;
    *) usage ;;
esac

resolve_output_directory
init_runtime
lock_state

case "$MODE" in
    status)
        if [ "$WAYBAR" = true ]; then
            if recording_state; then
                printf '{"text":"󰑊","tooltip":"Screen Recording: on","class":"active"}\n'
            else
                printf '{"text":""}\n'
            fi
            exit 0
        fi
        status
        ;;
    start) start "$TARGET" ;;
    stop) stop ;;
    toggle)
        if recording_state; then
            stop
        else
            start "$TARGET"
        fi
        ;;
esac
