#!/usr/bin/env sh
# Generated by the `rog-rgb` module; edits will be replaced.
# Missing asusctl or theme output is acceptable on unsupported machines.
set -eu
command -v asusctl >/dev/null 2>&1 || exit 0
f="{{color-ref:text}}"
[ -r "$f" ] || exit 0
color="$(tr -d '[:space:]#' < "$f")"
[ -n "$color" ] || exit 0
# Support both known asusctl command forms, preferring the newer `aura` form.
asusctl aura static -c "$color" 2>/dev/null || asusctl led-mode static -c "$color" 2>/dev/null || true
