[General]
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=1.5

[Theme]
ThemeDir = /usr/share/sddm/themes
Current  = gnist

[Wayland]
SessionDir = /usr/share/wayland-sessions
EnableHiDPI = true

[Users]
RememberLastUser = true
