# Generated by the `shell` module; edits will be replaced.

# Establish PATH before loading fragments from ~/.bashrc.d.
export PATH="$HOME/.local/bin:$PATH"

HISTSIZE={{history-size:int}}
HISTFILESIZE={{history-size:int}}
HISTCONTROL={{history-control:text}}
HISTTIMEFORMAT="%F %T "
shopt -s histappend checkwinsize globstar

# Keep user-facing defaults and fragments out of non-interactive shells.
if [[ $- == *i* ]]; then
    export EDITOR="{{editor:text}}"
    export VISUAL="{{editor:text}}"
    export PAGER="{{pager:text}}"
    export TERMINAL="{{term:text}}"
    export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

    if [ -d "$HOME/.bashrc.d" ]; then
        for f in "$HOME/.bashrc.d"/*.sh "$HOME/.bashrc.d"/*.bash; do
            [ -r "$f" ] && . "$f"
        done
    fi
fi
