# Generated by the `shell` module; edits will be replaced.
# Login shells may source this file; Bash prefers ~/.bash_profile or
# ~/.bash_login when either exists. Interactive non-login Bash uses ~/.bashrc.
export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
