-- Hyprland configuration generated by the smia `hypr` module; edits are replaced.
-- Values come from module inputs, so patch malm/modules/hypr/hypr.kdl, a profile,
-- or ~/.config/malm/local.kdl rather than this file. Keybinds follow below.

------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = {{global.display-internal-name:lua}},
    mode     = "{{global.display-internal-width}}x{{global.display-internal-height}}@{{global.display-internal-refresh}}",
    position = "{{global.display-internal-x}}x{{global.display-internal-y}}",
    scale    = "{{global.display-internal-scale}}",
})

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in     = {{gaps-in:lua}},
        gaps_out    = {{gaps-out:lua}},
        border_size = {{border-size:lua}},

        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        resize_on_border = false,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = {{rounding:lua}},
        rounding_power = 2,

        active_opacity   = {{active-opacity:lua}},
        inactive_opacity = {{inactive-opacity:lua}},

        shadow = {
            enabled      = {{shadow-enabled:lua}},
            range        = {{shadow-range:lua}},
            render_power = {{shadow-render-power:lua}},
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled  = {{blur:lua}},
            size     = {{blur-size:lua}},
            passes   = {{blur-passes:lua}},
            vibrancy = {{blur-vibrancy:lua}},
        },
    },

    animations = {
        enabled = {{animations:lua}},
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },

    input = {
        kb_layout  = {{xkb-layout:lua}},
        kb_variant = {{xkb-variant:lua}},
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        repeat_rate  = {{repeat-rate:lua}},
        repeat_delay = {{repeat-delay:lua}},

        follow_mouse = 1,
        sensitivity  = 0,

        numlock_by_default = {{numlock:lua}},

        touchpad = {
            natural_scroll       = {{touchpad-natural-scroll:lua}},
            tap_to_click         = {{touchpad-tap:lua}},
            disable_while_typing = {{touchpad-disable-while-typing:lua}},
        },
    },
})

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "{{cursor-size}}")
hl.env("HYPRCURSOR_SIZE", "{{cursor-size}}")

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("smia-session")
end)

--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1.0 }, { 0.32, 1.0 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1.0 } } })
hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0.0 }, { 0.1, 1.0 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10.0, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4.0, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7.0, bezier = "quick" })

------------------
---- GESTURES ----
------------------

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

----------------------
---- WINDOW RULES ----
----------------------

hl.window_rule({
    name           = "suppress-maximize-events",
    suppress_event = "maximize",
    match          = { class = ".*" },
})

-- XWayland drag surfaces steal focus without this.
hl.window_rule({
    name     = "fix-xwayland-drags",
    no_focus = true,
    match    = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
})

hl.window_rule({
    name  = "move-hyprland-run",
    move  = "20 monitor_h-120",
    float = true,
    match = { class = "hyprland-run" },
})

---------------
---- THEME ----
---------------

-- Gnist themes are trusted code in this system, so the current theme is applied
-- directly. The pcall only covers the first boot, before any theme is rendered.
local theme_ok, theme = pcall(dofile, os.getenv("HOME") .. "/.config/gnist/themes/current/hyprland.lua")
if theme_ok then
    hl.config(theme)
end

---------------------
---- KEYBINDINGS ----
---------------------

for workspace = 1, 10 do
    local key = workspace % 10
    hl.bind("{{mod-key}} + " .. key, hl.dsp.focus({ workspace = workspace }))
    hl.bind("{{mod-key}} + SHIFT + " .. key, hl.dsp.window.move({ workspace = workspace }))
end
