#!/usr/bin/env sh
# Generated by the `screenshot` module; edits will be replaced.
# Usage: gnist-screenshot [region|screen|window]
# Region is the default. Window capture uses Hyprland geometry and falls back
# to region selection where no portable active-window query exists.
set -eu

MODE="${1:-region}"
DIR="{{directory:text}}"
mkdir -p "$DIR"
FILE="$DIR/Screenshot-$(date +%Y-%m-%d_%H%M%S).png"

case "$MODE" in
    screen)
        grim "$FILE"
        ;;
    window)
        if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && command -v hyprctl >/dev/null 2>&1; then
            geom="$(hyprctl activewindow | awk '
                /^\tat:/   { at = $2 }
                /^\tsize:/ { size = $2 }
                END { gsub(",", "x", size); if (at != "" && size != "") print at " " size }')"
            if [ -n "$geom" ]; then
                grim -g "$geom" "$FILE"
            else
                geom="$(slurp)" || exit 0
                grim -g "$geom" "$FILE"
            fi
        else
            geom="$(slurp)" || exit 0
            grim -g "$geom" "$FILE"
        fi
        ;;
    region|*)
        geom="$(slurp)" || exit 0
        grim -g "$geom" "$FILE"
        ;;
esac
