#!/usr/bin/env sh
# Generated by the `screenshot` module; edits will be replaced.
# Usage: gnist-screenshot [region|screen|window]
# Region is the default. Window capture uses Hyprland geometry and falls back
# to region selection where no portable active-window query exists.
set -eu

MODE="${1:-region}"
DIR={{directory:shell-word}}
case "$DIR" in
    "~")
        [ -n "${HOME:-}" ] || { echo "gnist-screenshot: HOME is not set" >&2; exit 1; }
        case "$HOME" in /*) ;; *) echo "gnist-screenshot: HOME must be absolute" >&2; exit 1 ;; esac
        DIR="$HOME"
        ;;
    "~/"*)
        [ -n "${HOME:-}" ] || { echo "gnist-screenshot: HOME is not set" >&2; exit 1; }
        case "$HOME" in /*) ;; *) echo "gnist-screenshot: HOME must be absolute" >&2; exit 1 ;; esac
        DIR="$HOME/${DIR#\~/}"
        ;;
    /*) ;;
    *)
        echo "gnist-screenshot: output directory must be absolute or start with ~/" >&2
        exit 1
        ;;
esac
mkdir -p "$DIR"
FILE="$DIR/Screenshot-$(date +%Y-%m-%d_%H%M%S).png"

case "$MODE" in
    screen)
        grim "$FILE"
        ;;
    window)
        if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ] && command -v hyprctl >/dev/null 2>&1; then
            geom="$(hyprctl activewindow | awk '
                /^\tat:/   { at = $2 }
                /^\tsize:/ { size = $2 }
                END { gsub(",", "x", size); if (at != "" && size != "") print at " " size }')"
            if [ -n "$geom" ]; then
                grim -g "$geom" "$FILE"
            else
                geom="$(slurp)" || exit 0
                grim -g "$geom" "$FILE"
            fi
        else
            geom="$(slurp)" || exit 0
            grim -g "$geom" "$FILE"
        fi
        ;;
    region)
        geom="$(slurp)" || exit 0
        grim -g "$geom" "$FILE"
        ;;
    *)
        echo "gnist-screenshot: unknown mode: $MODE" >&2
        echo "Usage: gnist-screenshot [region|screen|window]" >&2
        exit 2
        ;;
esac
