#!/usr/bin/env sh
# Generated by the `wallpaper` module; edits will be replaced.
# The session service reads the current gnist background so theme changes do
# not require a session restart.
#
# Engine names must match the processes managed by the session manifest.
set -eu

IMAGE="{{image-src:text}}"
MODE="{{fill-mode:text}}"
ENGINE="{{engine:text}}"

resize_mode() {
    case "$MODE" in
        fill) printf '%s\n' crop ;;
        fit) printf '%s\n' fit ;;
        stretch) printf '%s\n' stretch ;;
        # swww and awww lack tiling, so preserve the image without resizing.
        center|tile) printf '%s\n' no ;;
    esac
}

wait_for_client() {
    client=$1
    for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
        "$client" query >/dev/null 2>&1 && return 0
        sleep 0.1
    done
    echo "gnist-wallpaper-apply: $client daemon did not become ready" >&2
    return 1
}

case "$ENGINE" in
    swaybg)
        exec swaybg -i "$IMAGE" -m "$MODE"
        ;;
    swww-daemon)
        if ! pgrep -x swww-daemon >/dev/null 2>&1; then
            swww-daemon &
        fi
        wait_for_client swww
        RESIZE=$(resize_mode)
        swww img "$IMAGE" --resize "$RESIZE"
        ;;
    hyprpaper)
        # Hyprpaper requires both directives even when one image covers all outputs.
        exec hyprpaper -c /dev/stdin <<EOF
preload = $IMAGE
wallpaper = ,$IMAGE
EOF
        ;;
    awww-daemon)
        if ! pgrep -x awww-daemon >/dev/null 2>&1; then
            awww-daemon &
        fi
        wait_for_client awww
        RESIZE=$(resize_mode)
        awww img "$IMAGE" --resize "$RESIZE"
        ;;
    *)
        echo "gnist-wallpaper-apply: unknown engine '$ENGINE'" >&2
        echo "expected: swaybg / swww-daemon / hyprpaper / awww-daemon" >&2
        exit 1
        ;;
esac
