#!/usr/bin/env sh
# Generated by the `appearance` module; edits will be replaced.
# Applies desktop interface settings once per session login.
# Gnist owns GTK theme, color-scheme, and icon-theme selection.
set -eu
command -v gsettings >/dev/null 2>&1 || exit 0
gsettings set org.gnome.desktop.interface font-name '{{font-name:text}} {{font-size:float}}' || true
gsettings set org.gnome.desktop.interface cursor-theme '{{cursor-theme:text}}' || true
gsettings set org.gnome.desktop.interface cursor-size {{cursor-size:int}} || true
