#!/usr/bin/env sh
# Generated by the `appearance` module; edits will be replaced.
# Applies desktop interface settings once per session login.
# The gnist theme engine owns these settings:
#   color-scheme  (per-theme *.mode files)
#   icon-theme    (per-theme icons.theme)
set -eu
command -v gsettings >/dev/null 2>&1 || exit 0
gsettings set org.gnome.desktop.interface font-name '{{font-name:text}} {{font-size:float}}' || true
gsettings set org.gnome.desktop.interface gtk-theme '{{gtk-theme:text}}' || true
gsettings set org.gnome.desktop.interface cursor-theme '{{cursor-theme:text}}' || true
gsettings set org.gnome.desktop.interface cursor-size {{cursor-size:int}} || true
